# Generated by Django 5.2.1 on 2025-05-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="screenings/")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("P", "Positive"),
                            ("N", "Negative"),
                            ("I", "Inconclusive"),
                        ],
                        max_length=1,
                    ),
                ),
                ("parasite_count", models.PositiveIntegerField()),
                ("confidence", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenings",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
